version: "3.8"

# https://github.com/amigoscode/mongodb-course
services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

volumes:
  data: {}

networks:
  default:
    name: mongodb_network
